stages:
  - test
  - build
  - deploy

default:
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY

flake8:
  stage: test
  image:
    name: ${DOCKER_REGISTRY}/flake8:4.0.1
    entrypoint: [""]
  before_script: []
  script:
    - flake8 --ignore=E501,E115 .
  tags:
    - arbat-build

build:
  stage: build
  only:
    - main
  script:
    - export RANDOM_SYMBOLS=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 20)
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || true
    - docker build 
      --progress=plain
      --build-arg REGISTRY=${DOCKER_REGISTRY}
       --build-arg RANDOM_SYMBOLS=$RANDOM_SYMBOLS
      --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME 
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      -t unireger:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - arbat-build

.deploy:
  stage: deploy
  variables:
    VAULT_ADDR: 'https://vault.arbat.dev:8200'
  script:
    - export VAULT_TOKEN=$(vault write -field=token auth/jwt/login role=opendata jwt=$CI_JOB_JWT)
    - vault kv get -field=api_key -format=json opendata/unireger > /APIKey.json
    - vault kv get -field=db_config -format=json opendata/unireger > /DBConfig.json
    - vault kv get -field=proxy_user_of_kind3 -format=json opendata/unireger > /ProxyUserOfKind3.json
    - docker stack deploy --with-registry-auth --prune -c docker-compose.yml $CI_PROJECT_NAME
    - stack_wait $CI_PROJECT_NAME
    - export CONTAINER_ID=$(docker ps -q --filter "name=${CI_PROJECT_NAME}")
    - echo "CONTAINER_ID=${CONTAINER_ID}" >> .env
    - echo "$CONTAINER_ID"

deploy_main:
  extends: .deploy
  only:
    - main
  variables:
    DOMAIN: .ad.dev.arbat.dev
  tags:
    - arbat-deploy
