version: '3.5'
x-defaults:
  &defaults
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  environment:
    - TZ=Europe/Moscow
    - CI_COMMIT_REF_NAME
    - CI_COMMIT_SHORT_SHA

services:
  app:
    << : *defaults
    secrets:
      - secret1
      - secret2
      - secret3
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 10240M
      restart_policy:
        condition: any
    networks:
      - default

secrets:
  secret1:
    file: /APIKey.json
  secret2:
    file: /DBConfig.json
  secret3:
    file: /ProxyUserOfKind3.json

networks:
  default:
    name: unireger
    attachable: true
