version: '3.5'
x-defaults:
  &defaults
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  environment:
    - TZ=Europe/Moscow
    - CI_COMMIT_REF_NAME
    - CI_COMMIT_SHORT_SHA
  labels:
    io.portainer.accesscontrol.teams: portainer-odata-$CI_PROJECT_NAME

services:
  app:
    << : *defaults
    secrets:
      - secret1
      - secret2
      - secret3
    deploy:
      resources:
        limits:
          memory: 1024M
      restart_policy:
        condition: any
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-net
        - traefik.http.services.unireger.loadbalancer.server.scheme=http
        - traefik.http.services.unireger.loadbalancer.server.port=5000
        - traefik.http.routers.unireger.rule=Host(`unireger${DOMAIN}`)
        - traefik.http.routers.unireger.service=unireger
        - traefik.http.routers.unireger.entrypoints=websecure
        - traefik.http.routers.unireger.tls=true
    networks:
      - default
      - traefik

secrets:
  secret1:
    file: /APIKey.json
  secret2:
    file: /DBConfig.json
  secret3:
    file: /ProxyUserOfKind3.json

networks:
  default:
    name: unireger
    attachable: true
  traefik:
    name: traefik-net
    external: true