version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    restart: unless-stopped
    hostname: gitlab.local
    ports:
      - "8000:80"   # Web UI / HTTP Git
      - "8022:22"   # SSH Git
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: "256m"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Внешний адрес должен совпадать с проброшенным портом
        external_url "http://localhost:8000"

        # Если будешь использовать SSH для Git (рекомендую)
        gitlab_rails['gitlab_shell_ssh_port'] = 8022

        # Чуть полегче для локалки (опционально)
        sidekiq['concurrency'] = 5
        puma['worker_processes'] = 2
        puma['threads_min'] = 1
        puma['threads_max'] = 2

        # Root-пароль при самом первом старте
        gitlab_rails['initial_root_password'] = 'ChangeMe123!'

        # Без HTTPS/почты
        letsencrypt['enable'] = false
        gitlab_rails['smtp_enable'] = false
        gitlab_rails['gitlab_email_enabled'] = false